### ISSUE TITLE
Home Button

### ISSUE THREAD

**Issue by SailorForSchool** [cse110-fq22-group40/cse110-fq22-group40#81]
# Adding a Persistent Button to the Homepage

## What?
We want our user to be able to click a button and see all their workspaces

## Where?
In the upper lefthand corner at all times with our logo

## How?
Have the reload button form the home screen persist

**Comment by billysud** [comment]
I made a branch with the changes tot the HTML where there is a home button on each page. Theoretically it should work but the styling is not amazing. I talked about this with Ryan and he agreed these changes should be the way to do it (by putting the HTML in the location for the anchor tags) but when testing it since the user profiles is not completed it does not load properly.
